### ISSUE TITLE
前端——每个请求前都会先发送option请求

### ISSUE THREAD

**Issue by clsaa** [clsaa/dop#141]
![image](https://clsaa-markdown-imgbed-1252032169.cos.ap-shanghai.myqcloud.com/very-java/2019-04-13-052357.png)

每个请求前都会先发送option请求，是因为要处理跨域吗？ @zhangfuli

**Comment by zhangfuli** [comment]
浏览器会首先使用 OPTIONS 方法发起一个预请求，判断接口是否能够正常通讯，如果不能就不会发送真正的请求过来，如果测试通讯正常，则开始真正的请求
