### ISSUE TITLE
流水线管理模块——设计实现问题——查看流水线,如果流水线没有运行过那么界面什么都没有,很尬, 能否在运行结果上边添加一个流水线的视图

### ISSUE THREAD

**Issue by clsaa** [clsaa/dop#166]
查看流水线,如果流水线没有运行过那么界面什么都没有,很尬, 能否在运行结果上边添加一个流水线的视图(和编辑流水线累死只不过只能看 不能编辑)

@zhangfuli

**Comment by zhangfuli** [comment]
我这样做的
![image](https://user-images.githubusercontent.com/17808702/56556058-75298d00-65c9-11e9-84e5-302911c805c4.png)
