### ISSUE TITLE
公共模块——UI——登录界面、侧边栏及header菜单的国际化

### ISSUE THREAD

**Issue by clsaa** [clsaa/dop#250]
![](https://clsaa-markdown-imgbed-1252032169.cos.ap-shanghai.myqcloud.com/very-java/2019-05-08-192536.png)

![](https://clsaa-markdown-imgbed-1252032169.cos.ap-shanghai.myqcloud.com/very-java/2019-05-08-192656.png)
登录页可直接改完全英文

@zhangfuli

**Comment by zhangfuli** [comment]
登录模块会根据用户的浏览器默认语言进行自动切换

**Comment by clsaa** [comment]
OK，那我的主页、设置、登出等UI要国际化一下 @zhangfuli
